[package]
name = "lit-html-macro"
version = "0.1.0"
authors = ["Richard <Richard>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true
quote="1"

[dependencies.syn]
version = "1"
features = ["full"]